vfbr/urls.py
from django.conf.urls import url, include, handler404
from django.contrib import admin
from django.conf import settings
from rest_framework import routers
from entities.api_views import *
from vocabs import api_views
from summaries.api_views import *


router = routers.DefaultRouter()
router.register(r'geojson', GeoJsonViewSet, basename='places')
router.register(r'metadata', api_views.MetadataViewSet)
router.register(r'skoslabels', api_views.SkosLabelViewSet)
router.register(r'skosnamespaces', api_views.SkosNamespaceViewSet)
router.register(r'skosconceptschemes', api_views.SkosConceptSchemeViewSet)
router.register(r'skoscollections', api_views.SkosCollectionViewSet)
router.register(r'skosconcepts', api_views.SkosConceptViewSet)
router.register(r'vfb', VerfachBuchViewSet)
router.register(r'vfb-entry', VfbEntryViewSet)
router.register(r'places', PlaceViewSet)
router.register(r'persons', PersonViewSet)
router.register(r'institutions', InstitutionViewSet)
router.register(r'anmerkungen', AnmerkungenViewSet)


urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^admin/', admin.site.urls),
    url(r'^transkribus/', include('transkribus.urls', namespace='transkribus')),
    url(r'^browsing/', include('browsing.urls', namespace='browsing')),
    url(r'^netvis/', include('netvis.urls', namespace="netvis")),
    url(r'^vocabs/', include('vocabs.urls', namespace='vocabs')),
    url(r'^summaries/', include('summaries.urls', namespace='summaries')),
    url(r'^vocabs-ac/', include('vocabs.dal_urls', namespace='vocabs-ac')),
    url(r'^entities-ac/', include('entities.dal_urls', namespace='entities-ac')),
    url(r'^books-ac/', include('books.dal_urls', namespace='books-ac')),
    url(r'^entities/', include('entities.urls', namespace='entities')),
    url(r'^charts/', include('charts.urls', namespace='charts')),
    url(r'^search/', include('haystack.urls')),
    url(r'^', include('webpage.urls', namespace='webpage')),
]

handler404 = 'webpage.views.handler404'

webpage/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView
from . import views

app_name = 'webpage'

favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)

urlpatterns = [
    url(r'^favicon\.ico$', favicon_view),
    url(r'^imprint', views.ImprintView.as_view(), name="imprint"),
    url(r'^$', views.GenericWebpageView.as_view(), name="start"),
    url(r'^accounts/login/$', views.user_login, name='user_login'),
    url(r'^logout/$', views.user_logout, name='user_logout'),
    url(r'^project-info/$', views.project_info, name='project_info'),
    url(r'^search-dist/$', views.SearchDistributor.as_view(), name='search_dist'),
    url(r'^(?P<template>[\w-]+)/$', views.GenericWebpageView.as_view(), name='staticpage'),
]

webpage/forms.py
# -*- coding: utf-8 -*-
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


class form_user_login(forms.Form):
    username = forms.CharField(label='Username', widget=forms.TextInput)
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(form_user_login, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', 'login'))

webpage/views.py
import requests
from copy import deepcopy

from django.conf import settings
from django.urls import reverse
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.template import RequestContext, loader
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
from django.contrib.auth import authenticate, login, logout

from . forms import form_user_login
from . metadata import PROJECT_METADATA as PM


def get_imprint_url():
    try:
        base_url = settings.ACDH_IMPRINT_URL
    except AttributeError:
        base_url = "https://provide-an-acdh-imprint-url/"
    try:
        redmine_id = settings.REDMINE_ID
    except AttributeError:
        redmine_id = "go-register-a-redmine-service-issue"
    return "{}{}".format(base_url, redmine_id)


class ImprintView(TemplateView):
    template_name = 'webpage/imprint.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        imprint_url = get_imprint_url()
        r = requests.get(get_imprint_url())

        if r.status_code == 200:
            context['imprint_body'] = "{}".format(r.text)
        else:
            context['imprint_body'] = """
            On of our services is currently not available. Please try it later or write an email to
            acdh@oeaw.ac.at; if you are service provide, make sure that you provided ACDH_IMPRINT_URL and REDMINE_ID
            """
        return context


class SearchDistributor(RedirectView):
    query_string = True

    def get_redirect_url(self, *args, **kwargs):
        search_loc = self.request.GET.get('where')
        query_param = self.request.GET.get('q')
        if search_loc == 'vfb':
            return f"{reverse('haystack_search')}?q={query_param}"
        else:
            return f"{reverse('transkribus:trp_hits')}?query={query_param}"


class GenericWebpageView(TemplateView):
    template_name = 'webpage/index.html'

    def get_context_data(self, **kwargs):
        context = super(GenericWebpageView, self).get_context_data(**kwargs)
        context['apps'] = settings.INSTALLED_APPS
        return context

    def get_template_names(self):
        template_name = "webpage/{}.html".format(self.kwargs.get("template", 'index'))
        try:
            loader.select_template([template_name])
            template_name = "webpage/{}.html".format(self.kwargs.get("template", 'index'))
        except:
            template_name = "webpage/index.html"
        return [template_name]


#################################################################
#               views for login/logout                          #
#################################################################

def user_login(request):
    if request.method == 'POST':
        form = form_user_login(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])
            if user and user.is_active:
                login(request, user)
                return HttpResponseRedirect(request.GET.get('next', '/'))
            return HttpResponse('user does not exist')
    else:
        form = form_user_login()
        return render(request, 'webpage/user_login.html', {'form': form})


def user_logout(request):
    logout(request)
    return render(request, 'webpage/user_logout.html')


def handler404(request, exception):
    return render(request, 'webpage/404-error.html', locals())


def project_info(request):

    """
    returns a dict providing metadata about the current project
    """

    info_dict = deepcopy(PM)

    if request.user.is_authenticated:
        pass
    else:
        del info_dict['matomo_id']
        del info_dict['matomo_url']
    info_dict['base_tech'] = 'django'
    info_dict['framework'] = 'djangobaseproject'
    return JsonResponse(info_dict)

webpage/templates/webpage/404-error.html
{% extends "webpage/base.html" %}
{% load static %}

{% block content %}
<div class="container">
<div style="text-align: center;">
    
    <h2>We're sorry, the page you requested cannot be found.</h2>
    <p style="text-align: center">The page you're trying to access may not exist anymore or may have been moved. Try accessing it again from our site's homepage. Please also make sure that your spelling is correct.</p>
    <p style="text-align: center">If the problem persists, please report it as an issue <a href="https://github.com/acdh-oeaw/vfbr/issues">here</a>. Thank you!</p>

</div>
</div>
{% endblock %}

webpage/templates/webpage/about.html
{% extends "webpage/base.html" %}
{% load static %}
{% load webpage_extras %}
{% block title %} About {% endblock %}
{% block content %}
<div class="container">
    <div class="card">
        <div class="card-header">
            <h1 class="card-title">{% projects_metadata 'title' %}</h1>
        </div>
        <div class="card-body">
            <div>
                <p>
                    {% projects_metadata 'description' %}
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

webpage/templates/webpage/confirm_delete.html
{% extends "webpage/base.html" %}
{% block content %}
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title">Confirm delete</h3>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <form action="" method="post">
                    {% csrf_token %}
                    <h4>
                        Are you sure you want to delete: <strong>{{ object }}</strong> ?
                    </h4>
                    <input  class="btn btn-danger" type="submit" value="Yes, I want to delete" />
                </form>
            </div>
            <div class="modal-footer">
                <input  class="btn" type="submit" value="No, bring me back" onclick="goBack()" />
            </div>
        </div>
    </div>
    <script>
        function goBack() {
            window.history.back();
        }
    </script>
{% endblock content %}

webpage/templates/webpage/imprint.html
{% extends "webpage/base.html" %}
{% load static %}
{% load webpage_extras %}
{% block title %} Imprint {% endblock %}
{% block content %}
<div class="container">
<div class="card imprint">
<div class="card-body">
    {{ imprint_body|safe }}
</div>
</div>
</div>
{% endblock %}

webpage/templates/webpage/index.html
{% extends "webpage/base.html" %}
{% load static %}
{% load webpage_extras %}
{% block content %}

<header class="masthead text-white text-center">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-xl-9 mx-auto" style="background-color: #b09b7fb8; padding-top:3em">
        <h1 class="mb-5">Verfachbuch-Regesten</h1>
        <h1 class="mb-5">Mittleres Pustertal 1750-1800</h1>
        <p>
          <small>Foto © <a href="https://www.tirol.gv.at/kunst-kultur/landesarchiv/" style="color:white">Tiroler Landearchiv</a>, Landgericht Mieders, Aktenserie Fasz. 7, Pos. 5 (Inventare 1754), Nr. 29 (Inventar des Urban Sachser), Blatt
            3v-4r.“</small>
        </p>
      </div>
      <div class="col-md-12 mx-auto">
        <form method="get" action="{% url 'webpage:search_dist' %}" style="margin: 2em">
          <div class="form-row">
            <div class="col-md-4">
              <select class="custom-select custom-select-lg mb-3" name="where">
                <option value="vfb">Suche in Metadaten</option>
                <option value="ft">Suche in Volltexten</option>
              </select>
            </div>
            <div class="col-md-4">
              <input type="search" class="form-control form-control-lg" placeholder="z.B. 'Gasser'" required name="q">
            </div>
            <div class="col-md-4">
              <button type="submit" class="btn btn-block btn-lg btn-primary" style="background-color:#b08968; border-color:#b08968;">Los!</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</header>

<section class="showcase">
  <div class="container-fluid p-0">
    <div class="row no-gutters justify-content-md-center">
      <div class="col-lg-6 order-lg-1 my-auto showcase-text">
        <p>
          Im Rahmen des von FWF und Land Tirol geförderten Projekts <a href="https://pf.fwf.ac.at/de/wissenschaft-konkret/project-finder/38419">„Lesen im Alpental. Privater Buchbesitz in Tirol 1750–1800“</a> wurden von Michael Span die Verfachbücher des Landgerichts St. Michaelsburg, des Stadtgerichts Brunecks sowie des Oberamtsgerichts Brunnecks für den Zeitraum 1750 bis 1800 fotografiert und für den eigenen Gebrauch gemeinsam mit Michael Prokosch mit Regesten versehen.
        </p>
        <p>
          Die vorliegende Website stellt diese ursprünglich nicht für die Veröffentlichung vorgesehenen Forschungsdaten nun der interessierten Öffentlichkeit zur Verfügung.
        </p>
        <p>
          Konkret werden drei Ebenen der Erschließung der Verfachbücher zugänglich gemacht, nämlich
          <ul>
            <li>
              die <a href="{% url 'webpage:staticpage' template='volltexte' %}">Faksimiles</a> samt automatisch, unter Verwendung von <a href="https://transkribus.eu/Transkribus/">Transkribus</a>, generiertem Volltext beziehungsweise Transkription,
            </li>
            <li>
              <a href="{% url 'webpage:staticpage' template='regesten' %}">Kurzregeste</a> zu den einzelnen Einträgen in den Verfachbüchern,
            </li>
            <li>
              sowie systematische Beschreibungen von Verfachbucheinträgen mit Auflistungen von Besitzungen  (<a href="{% url 'webpage:staticpage' template='inventarbeschreibungen' %}">Inventaren</a>).
            </li>
          </ul>
        </p>
      </div>
    </div>
  </div>
</section>

{% endblock %}

webpage/templates/webpage/inventarbeschreibungen.html
{% extends "webpage/base.html" %}
{% load static %}
{% load webpage_extras %}
{% block content %}

<section class="showcase">
  <div class="container-fluid p-0">
    <div class="row no-gutters justify-content-md-center">
      <div class="col-lg-6 order-lg-1 my-auto showcase-text">
        <h1>Inventarbeschreibungen</h1>
        <p>Text in Arbeit</p>
      </div>
    </div>
  </div>
</section>

{% endblock %}

webpage/templates/webpage/personen-orte.html
{% extends "webpage/base.html" %}
{% load static %}
{% load webpage_extras %}
{% block content %}

<section class="showcase">
  <div class="container-fluid p-0">
    <div class="row no-gutters justify-content-md-center">
      <div class="col-lg-6 order-lg-1 my-auto showcase-text">
        <h1>Personen und Orte</h1>
        <p>
          Eine große Herausforderung im Zusammenhang mit der Auswertung von (personenbezogenen) Massenquellen stellt die
          <ul>
            <li>
              Identifikation (Wer war der in einer Quelle genannte Hans Maier?),
            </li>
            <li>
              Disambiguierung (Ist der auf Seite 123 genannte Hans Maier derselbe Hans Maier wie der auf Seite 200?)
            </li>
            <li>
              und Referenzierung (Wie kann ich eindeutig ausdrücken, dass Hans Maier von Seite 123 derselbe Hans Maier wie der von Seite 200, aber nicht derselbe wie der von Seite 44 ist?) von Personen dar.
            </li>
          </ul>
          Dies ist eine Herausforderung, die in frühneuzeitlichen Quellen durch die variablen Schreibweisen von Vor,- Nach-, Haus-, Hof- oder Ortsnamen sowie von Berufs- oder Rollenbezeichnungen noch zusätzlich vergrößert wird.
        </p>
        <p>
          Bei der Erstellung der Verfachbuchregeste sowie der Inventarbeschreibungen wurden Personen daher anhand
          <ul>
            <li>
              von verwandtschaftlichen Beziehungen (z. B. Tochter von …),
            </li>
            <li>
              der jeweiligen Funktion im Rechtsgeschäft (z. B. Schreiber ...),
            </li>
            <li>
              von Berufs- und/oder Standesbezeichnungen (z. B. Wirt und Bürger des Rates)
            </li>
            <li>
              sowie der Angaben zu Wohn- oder Wirkungsorten
            </li>
            so gut wie möglich identifiziert und disambiguiert.
          </ul>
        </p>
        <p>
          Dazu wurden sowohl die Namen (Vor-, Nach-, Mädchen-, Haus- oder Hofname) als auch die Berufs- und Tätigkeitsbezeichnungen der in den Quellen genannten Personen normalisiert beziehungsweise um gängige Schreibweisen erweitert, wie etwa das
          folgende Beispiel zeigt:
          <ul>
            <li>
              Mathes [Matthias/Matthäus] Porger [Porgger/Parger/Pargger] (Zimmermann), St. Veit in Prags (Oberamtsgericht Bruneck), (Vater der Ursula Porgerin [Porggerin/Pargerin/Parggerin])
            </li>
          </ul>
        </p>
        <p>
          Bei der Überführung der Daten aus ihren ursprünglichen Formaten (Word und Excel) wurde versucht, diese semistrukturierten Informationen wie eben Berufs- und Ortsbezeichnungen sowie (verwandtschaftliche) Beziehungen zwischen den genannten
          Personen zu extrahieren und als eigene Datensätze abzulegen. Aus dem ersten Beispiel entstanden somit unter anderem zwei Personen- und zwei Ortseinträge, die allesamt miteinander verknüpft sind.
        </p>
        <div class="card">
          <div class="card-header">Person</div>
          <div class="card-body">
            <table class="table table-hover table-sm">
              <tr>
                <th>Vorname</th>
                <td>Mathes [Matthias/Matthäus]</td>
              </tr>
              <tr>
                <th>Nachname</th>
                <td>Porger [Porgger/Parger/Pargger]</td>
              </tr>
              <tr>
                <th>Beruf</th>
                <td>Zimmermann</td>
              </tr>
              <tr>
                <th>familiäre Verbindungen</th>
                <td>Vater von Ursula Porgerin [Porggerin/Pargerin/Parggerin]</td>
              </tr>
            </table>
          </div>
        </div>
        <div class="card">
          <div class="card-header">Person</div>
          <div class="card-body">
            <table class="table table-hover table-sm">
              <tr>
                <th>Vorname</th>
                <td>Ursula</td>
              </tr>
              <tr>
                <th>Nachname</th>
                <td>Porgerin [Porggerin/Pargerin/Parggerin]</td>
              </tr>
              <tr>
                <th>Beruf</th>
                <td>Zimmermann</td>
              </tr>
              <tr>
                <th>familiäre Verbindungen</th>
                <td>Tochter von Mathes [Matthias/Matthäus] Porger [Porgger/Parger/Pargger</td>
              </tr>
            </table>
          </div>
        </div>
        <div class="card">
          <div class="card-header">Ort</div>
          <div class="card-body">
            <table class="table table-hover table-sm">
              <tr>
                <th>Name</th>
                <td>St. Veit in Prags</td>
              </tr>
              <tr>
                <th>Teil von</th>
                <td>Oberamtsgericht Bruneck</td>
              </tr>
            </table>
          </div>
        </div>
        <div class="card">
          <div class="card-header">Ort</div>
          <div class="card-body">
            <table class="table table-hover table-sm">
              <tr>
                <th>Name</th>
                <td>Oberamtsgericht Bruneck</td>
              </tr>
              <tr>
                <th>Übergeordnete Einheit von</th>
                <td>St. Veit in Prags</td>
              </tr>
            </table>
          </div>
        </div>
        <p>
          Eine solche Datenstruktur ermöglicht nun
          <ul>
            <li>
              zielgerichtete Suchabfragen (z. B. alle Zimmermänner aus dem Oberamtsgericht Bruneck),
            </li>
            <li>
              das Nachzeichnen familiäre Netzwerke,
            </li>
            <li>
              ungefähre statistische Abfragen (Verteilung der Berufe).
            </li>
          </ul>
        </p>
        <p>
          Die Extraktion der verschiedenen Informationen erfolgte großteils mittels statistischer Modelle. Je nach Informationseinheit (Beruf, Ort, Geschlecht, Name, …) wurden zwischen 100 und 1000 Datensätze manuell von Peter Andorfer annotiert um damit einen Algorithmus zu trainieren, der in der Lage ist, die gewünschten Informationen zu finden. Die einzelnen Modelle erreichten dabei zwischen 75 und 98 Prozent Genauigkeit.
        </p>
        <p>
            Beim Datenimport wurden außerdem Einträge mit identischer Zeichenfolge zusammengeführt. Dies ist insofern zu rechtfertigen, da ja bereits beim Anlegen der ursprünglichen Einträge darauf geachtet wurde, idente Personen exakt gleich und in der oben beschriebenen Art und Weise zu bezeichnen, eben um die eindeutige Identifikation einer Person gewährleisten zu können.
          </p>
          <p>
            Da die ursprünglichen Einträge jedoch ohne technische Unterstützung „händisch“ verfasst wurden, können Tippfehler nicht zur Gänze ausgeschlossen werden. Vor diesem Hintergrund sei hier einmal mehr darauf hingewiesen, dass sich die vorliegende Website aus Arbeitsdaten für den internen Gebrauch speist. Dies hat jedoch zur Folge, dass in der Datenbank potenzielle Dubletten anzutreffen sind. Hinzu kommt, dass für diese Datenbank die Datensätze aus zwei getrennt erstellten Arbeitsbehelfen, mit jeweils eigenen Konventionen, zusammengeführt wurden.
          </p>
          <p>
            Wie man diese Daten möglichst automatisiert verbessern kann, ist Gegenstand der aktuellen Arbeiten am Forschungsprojekt. Erste Ergebnisse werden im Rahmen der <a href="https://www.agrargeschichte.de/pagecontents-ansehen-1329-80-0-VW5zZXJlIFRhZ3VuZ2Vudec0.htm">Jahrestagung der Gesellschaft für Agrargeschichte in Kooperation mit der Arbeitsgemeinschaft Digitale Geschichtswissenschaft des Verbands der Historiker und Historikerinnen Deutschlands im Juni 2020</a> von Michael Span und Peter Andorfer präsentiert werden.
          </p>
          <h2>Normalisierung von Personennamen</h2>
          <p>
            Konventionen in Word/Excel Dokumenten angesetzt -> v.a. auf Auffindbarkeit geachtete; sprich mögliche alternative Schreibweisen in eckige Klammer gesetzt und mit ‘/’ getrennt. Als ein Beispiel sei etwa „Georg Paur [Baur/Bauer] (Bänderweber), Stefansdorf“ angeführt. Diese Person kann in einem Word oder Exceldokument gefunden werden, egal ob nach „Bauer”, „Baur“ oder „Paur“ gesucht wurde.
          </p>
          <p>
            Im Zuge des Datenimports wurden die Namensansetzung noch weiter vereinheitlicht.
            <ul>
              <li>
                In einem ersten Verarbeitungsschritt wurden alle  Namensvarianten extrahiert und alphabetisch geordnet. Aus „Paur [Baur/Bauer]“ wird somit „Bauer/Baur/Paur”.
              </li>
              <li>
                Ein zweiter Schritt versucht potentielle Dubletten zusammenzuführen. Solche Dubletten können etwa dadurch entstehen, dass nicht immer alle Namensvarianten angeführt wurden oder aber dass aufgrund der Schreibweise in den Quellen nicht jede Variante wahrscheinlich ist. Die Namensanstzungen werden dafür stets zur umfassendern Bezeichnung zusammengeführt. Aus „Bauer/Baur“ wird somit „Bauer/Baur/Paur”.
              </li>
            </ul>
            </p>
            <p>
              Ähnliche Schritte wurden auch im Zusammenhang mit Vornamen gesetzt, wobei hier bereits in den Quellen weniger Schreibvarianten anzutreffen sind, mit Ausnahme von Hans/Johann, Vitus/Veit sowie Mathes/Matthias/Matthäus. Nicht zusammengeführt werden Johann bzw Hans mit Johannes da aufgrund der Quellen davon auszugehen ist, dass Johann und Johannes auch von den Zeitgenossen als unterschiedliche Namen verstanden wurden.
            </p>
      </div>
    </div>
</section>

{% endblock %}

webpage/templates/webpage/regesten.html
{% extends "webpage/base.html" %}
{% load static %}
{% load webpage_extras %}
{% block content %}

<section class="showcase">
  <div class="container-fluid p-0">
    <div class="row no-gutters justify-content-md-center">
      <div class="col-lg-6 order-lg-1 my-auto showcase-text">
        <h1>Regesten von Verfachbucheinträgen</h1>
        <p>
          Auf der Suche nach Einträgen in den Verfachbüchern der Verwaltungseinheiten St. Michaelsburg, Stadtgericht Bruneck und Oberamtsgericht Bruneck, die für das Projekt „Lesen im Alpental. Privater Buchbesitz in Tirol 1750–1800“ relevant waren, mussten zwangsläufig sämtliche Verfachbücher des Untersuchungs(zeit)raums durchgesehen werden. Als interne Arbeitsbehelfe wurden dabei von Michael Span und Michael Prokosch Kurzregesten der einzelnen Verfachbucheinträge angefertigt, in denen
         <ul>
            <li>
              neben dem Typus des im Eintrag beschriebenen Rechtsgeschäfts,
            </li>
            <li>
              die wichtigsten handelnden Personen
            </li>
            <li>
              sowie die genaue Position (Blatt- beziehungsweise Seitenzahlen sowie Nummerierung) des Eintrags im Verfachbuch
            </li>
            </ul>
          festgehalten wurden.
        </p>
        <p>
          Hinsichtlich der Vollständigkeit der Regesten zu den Verfachbüchern des Landgerichts St. Michaelsburg muss jedoch einschränkend folgendes bemerkt werden: Aufgezeichnet wurden hier jene gerichtlichen Vorgänge, die potenziell die Erstellung eines Inventars veranlassen konnten. Die Auswahl erfolgte anhand der den Verfachbucheinträgen beigefügten „Kurztitel". Da diese mitunter nur rudimentäre Auskunft über die jeweiligen Einträge erteilen, ist mit gewissen Unschärfen zu rechnen. Definitiv vollständig verzeichnet sind jedoch auch hier jene Verfachbucheinträge, die Inventare enthalten. Das betrifft auch Fälle, in denen Inventare nicht „vollständig“ vorhanden sind, respektive lediglich Teile der Habe einzelner Personen verzeichnet wurden.
        </p>
        <p>
          Diese als Textdateien geführten Arbeitsbehelfe wurden in weiterer Folge von Peter Andorfer mithilfe diverser Scripte prozessiert und die darin gesammelten Informationen in eine Datenbank überführt, mit dem Ziel, diese Forschungsdaten einerseits einem größeren Publikum zugänglich und andererseits quantitativ auswertbar zu machen.
        </p>
        <p>
          Die Strukturierung und Anreicherung der originär nur gering formalisierten Daten erfolgte weitgehend automatisch und ohne umfassende manuelle kuratierende Eingriffe (mehr dazu im Abschnitt <a href="{% url 'webpage:staticpage' template='personen-orte' %}">Personen und Orte</a>). Das hat zur Folge, dass die hier veröffentlichten Daten mit Fehlern behaftet sein können, wie beispielsweise fälschliche Zuschreibungen von Vor- und Nachnamen von Personen, duplizierte Datensätze sowie falsch zusammengeführte Einträge. Eine fortlaufende manuelle Kuratierung der Daten ist jedoch angedacht.
        </p>
      </div>
    </div>
  </div>
</section>

{% endblock %}

webpage/templates/webpage/user_login.html
{% extends "webpage/base.html" %}
{% block content %}
<div class="container">
    <br />
    {% if form.errors %}
        <p style="color:red;">Please correct the error{{ form.errors|pluralize }} below.</p>
    {% endif %}
    {% load crispy_forms_tags %}
    {% crispy form form.helper %}
</div>
{% endblock %}

webpage/templates/webpage/user_logout.html
{% extends "webpage/base.html" %}
{% block title %}logout{% endblock %}
{% block content %}
<div class="jumbotron container">
    <h1>Sayōnara!</h1>
    <p>You've signed out</p>
</div>
{% endblock content %}